import { StyleSheet, Text, View } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { radius, typography } from "../../theme/tokens";
import { useTheme } from "../../theme/useTheme";

type AutoGeneratedBannerProps = {
  name: string;
  category?: string | null | undefined;
};

const stars = [
  { top: "18%", left: "9%", size: 2, opacity: 0.5 },
  { top: "28%", left: "76%", size: 3, opacity: 0.42 },
  { top: "62%", left: "18%", size: 2, opacity: 0.36 },
  { top: "74%", left: "88%", size: 2, opacity: 0.44 },
  { top: "46%", left: "54%", size: 2, opacity: 0.28 },
] as const;

const palettes = [
  ["#7C5CFF", "#00D4FF", "#FF4FD8"],
  ["#00D4FF", "#37E29F", "#7C5CFF"],
  ["#FF4FD8", "#7C5CFF", "#111735"],
  ["#6548EE", "#008FB3", "#C920A7"],
] as const;

export function AutoGeneratedBanner({ name, category }: AutoGeneratedBannerProps) {
  const theme = useTheme();
  const initials = getInitials(name);
  const paletteIndex =
    [...name].reduce((sum, char) => sum + char.charCodeAt(0), 0) % palettes.length;
  const colors = palettes[paletteIndex] ?? palettes[0];

  return (
    <View style={styles.root}>
      <LinearGradient
        colors={[colors[0], colors[1], colors[2]]}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        style={StyleSheet.absoluteFill}
      />
      <LinearGradient
        colors={["rgba(9,10,18,0.08)", "rgba(9,10,18,0.68)"]}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        style={StyleSheet.absoluteFill}
      />
      <View style={styles.waveOne} />
      <View style={styles.waveTwo} />
      {stars.map((star) => (
        <View
          key={`${star.top}-${star.left}`}
          style={[
            styles.star,
            {
              top: star.top,
              left: star.left,
              width: star.size,
              height: star.size,
              borderRadius: star.size / 2,
              opacity: star.opacity,
            },
          ]}
        />
      ))}
      <Text style={styles.initials}>{initials}</Text>
      {category ? (
        <View
          style={[
            styles.categoryPill,
            {
              backgroundColor: `${theme.colors.background}66`,
              borderColor: "rgba(255,255,255,0.16)",
            },
          ]}
        >
          <Text style={styles.categoryText} numberOfLines={1}>
            {category}
          </Text>
        </View>
      ) : null}
    </View>
  );
}

function getInitials(value: string) {
  return value
    .split(" ")
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    overflow: "hidden",
  },
  waveOne: {
    position: "absolute",
    width: "120%",
    height: 88,
    left: "-10%",
    bottom: -24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: radius.pill,
    transform: [{ rotate: "-7deg" }],
  },
  waveTwo: {
    position: "absolute",
    width: "96%",
    height: 72,
    right: "-16%",
    top: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: radius.pill,
    transform: [{ rotate: "15deg" }],
  },
  star: {
    position: "absolute",
    backgroundColor: "#FFFFFF",
  },
  initials: {
    position: "absolute",
    right: 16,
    bottom: -12,
    color: "rgba(255,255,255,0.16)",
    fontSize: 88,
    fontWeight: "900",
    letterSpacing: 0,
  },
  categoryPill: {
    position: "absolute",
    top: 10,
    right: 10,
    maxWidth: 132,
    borderWidth: 1,
    borderRadius: radius.pill,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  categoryText: {
    color: "#FFFFFF",
    fontSize: typography.tiny,
    fontWeight: "900",
    textTransform: "uppercase",
  },
});
