import { Image } from "expo-image";
import { StyleSheet, View } from "react-native";
import { AutoGeneratedBanner } from "./AutoGeneratedBanner";

type CommunityBannerProps = {
  uri?: string | null;
  name: string;
  category?: string | null | undefined;
};

export function CommunityBanner({ uri, name, category }: CommunityBannerProps) {
  return (
    <View style={styles.root}>
      {uri ? (
        <Image source={{ uri }} style={StyleSheet.absoluteFill} contentFit="cover" />
      ) : (
        <AutoGeneratedBanner name={name} category={category} />
      )}
      <View style={styles.shade} />
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  shade: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(9,10,18,0.10)",
  },
});
